version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./server:/usr/src/app/server
      - ./log-management:/usr/src/app/log-management
      - ./waf:/usr/src/app/waf
    environment:
      - NODE_ENV=production
    command: npm start

  server2:
    image: node:16
    working_dir: /usr/src/app
    volumes:
      - D:/sample/ddos:/usr/src/app
    command: node server2.js

  log-management:
    image: node:16
    working_dir: /usr/src/app
    volumes:
      - D:/sample/log-management:/usr/src/app
    command: node index.js

  waf:
    image: node:16
    working_dir: /usr/src/app
    volumes:
      - D:/sample/waf:/usr/src/app
    command: node server.js

  # Optional: Add a service for MongoDB, Redis, etc.
  # db:
  #   image: mongo:6
  #   ports:
  #     - "27017:27017"
