version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    environment:
      - NODE_ENV=production
    command: npm start

  # Optional: Add a service for MongoDB, Redis, etc.
  # db:
  #   image: mongo:6
  #   ports:
  #     - "27017:27017"
